### PR TITLE
Walkthroughs and colab data

### PR DESCRIPTION
**Pull request by SimonTopp**
Added Intro notebook, lightweight data set to run in colab, and started to look at DO project.

### CODE REVIEW

**Comment by SimonTopp** [comment]
@jdiaz4302, two questions for you in this PR:
- It includes the stripped down data for the `Intro to XAI` notebook.  You good with that living in here at least for now?
- The DO project is all in TF, so I rewrote the EG function in TensorFlow.  I'm just getting started on the notebook, but so far the outputs from the TF version look like you'd expect.  I'm shooting to wrap up a draft of the full notebook today, but you mind putting a second set of eyes on the TF function when you have a second?  Also, notice that it's a multitask LSTM so I added a `task_focus` argument. From `06_02_DO_Walkthrough.ipnb`: 

```
def expected_gradients_tf(x, x_set, model, n_samples, temporal_focus=None,task_focus=1):
    
    n_series = x_set.shape[0]
    num_vars = x_set.shape[2]
    seq_len = x_set.shape[1]
    
    for k in range(n_samples):
        # SAMPLE A SERIES FROM OUR DATA
        rand_seq = np.random.choice(n_series) # rand_time may be more accurate
        baseline_x = x_set[rand_seq]

        # SAMPLE A RANDOM SCALE ALONG THE DIFFERENCE
        scale = np.random.uniform()

        # SAME IG CALCULATION
        x_diff = x - baseline_x
        #print(x_diff)
        curr_x = baseline_x + scale*x_diff
        curr_x = tf.convert_to_tensor(curr_x)
        with tf.GradientTape() as gtape:
            gtape.watch(curr_x)
            if temporal_focus == None:
                y = model(curr_x)[:,:,task_focus]
            else:
                y=model(curr_x)[:,temporal_focus,task_focus]

        gradients = gtape.gradient(y, curr_x, tf.ones_like(y))
        #print(gradients)
        if k == 0:
            expected_gradients = x_diff*gradients * 1/n_samples
        else:
            expected_gradients = expected_gradients + ((x_diff*gradients) * 1/n_samples)
     return(expected_gradients.numpy())
```

**Comment by jdiaz4302** [comment]
I have no problem with the data being here, and it is only 4.1mb, so I don't think size is an issue.

Also, the EG looks good - just changing the torch gradient functions to tf, and those do seem like the right ones. Nice job doing the translation 😎 

I'd be curious to know if that `tf.ones_like(y)` behaves the same as the torch ones within `gtape.gradient` (i.e., if you do negative ones does it flip the sign, if you do zero does it zero the magnitude - essentially a scale). Also, interested to know the compute time (understanding that this is a different project and data so it won't be 1:1 comparable)

**Comment by SimonTopp** [comment]
Thanks man!  Looks like we get similar behavior to the torch implementation.  I don't remember the torch compute time off the top of my head for comparison, but this seems fairly quick.
As written
image
Negative ones
image
Zeros
image

**Comment by jdiaz4302** [comment]
Yeah, 30sec is the same ballpark. The river-dl model, data and using `torch` was ~2mins.

**Comment by jdiaz4302** [comment]
Tangentially, it's interesting that you're seeing those little bumps in attribution further back in time, I don't recall seeing that as much in the temperature work!

**Comment by SimonTopp** [comment]
Ya!  In generally the DO model seems to have a little longer memory. Precip is the only one that seems to persist throughout the sequence, but a lot of the other variables seem to influence within ~2 months rather than ~1 month.  Pretty interesting.

**Pull request merged**
